/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'product-categories': ProductCategory;
    products: Product;
    'solution-categories': SolutionCategory;
    solutions: Solution;
    categories: Category;
    posts: Post;
    'case-studies': CaseStudy;
    jobs: Job;
    leads: Lead;
    'job-applications': JobApplication;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'solution-categories': SolutionCategoriesSelect<false> | SolutionCategoriesSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: 'admin'[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  name: string;
  /**
   * Tự sinh từ tên. Để trống để hệ thống tự tạo.
   */
  slug?: string | null;
  description?: string | null;
  /**
   * Số nhỏ hiển thị trước.
   */
  sortOrder?: number | null;
  status: 'draft' | 'published';
  catalogManaged?: boolean | null;
  catalogSource?: string | null;
  catalogSourcePath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  category?: (number | null) | ProductCategory;
  /**
   * Hiển thị trên thẻ sản phẩm và mega menu.
   */
  shortDescription?: string | null;
  overview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  keyPoints?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  detailSections?:
    | {
        heading: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        bullets?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctas?:
    | {
        label: string;
        /**
         * Đường dẫn nội bộ, ví dụ: /lien-he
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  relatedProducts?: (number | Product)[] | null;
  relatedSolutions?: (number | Solution)[] | null;
  /**
   * Tối ưu hiển thị trên công cụ tìm kiếm và mạng xã hội.
   */
  seo?: {
    /**
     * Tiêu đề hiển thị trên Google (≈ 60 ký tự).
     */
    metaTitle?: string | null;
    /**
     * Mô tả ngắn hiển thị trên Google (≈ 160 ký tự).
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Để trống để dùng URL mặc định của trang.
     */
    canonical?: string | null;
  };
  image?: (number | null) | Media;
  /**
   * Số nhỏ hiển thị trước.
   */
  sortOrder?: number | null;
  status: 'draft' | 'published';
  catalogManaged?: boolean | null;
  catalogSource?: string | null;
  catalogSourcePath?: string | null;
  /**
   * Tự sinh từ tên. Để trống để hệ thống tự tạo.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  name: string;
  category?: (number | null) | SolutionCategory;
  shortDescription?: string | null;
  overview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  painPoints?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  detailSections?:
    | {
        heading: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        bullets?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctas?:
    | {
        label: string;
        /**
         * Đường dẫn nội bộ, ví dụ: /lien-he
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  recommendedProducts?: (number | Product)[] | null;
  /**
   * Tối ưu hiển thị trên công cụ tìm kiếm và mạng xã hội.
   */
  seo?: {
    /**
     * Tiêu đề hiển thị trên Google (≈ 60 ký tự).
     */
    metaTitle?: string | null;
    /**
     * Mô tả ngắn hiển thị trên Google (≈ 160 ký tự).
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Để trống để dùng URL mặc định của trang.
     */
    canonical?: string | null;
  };
  image?: (number | null) | Media;
  /**
   * Số nhỏ hiển thị trước.
   */
  sortOrder?: number | null;
  status: 'draft' | 'published';
  catalogManaged?: boolean | null;
  catalogSource?: string | null;
  catalogSourcePath?: string | null;
  /**
   * Tự sinh từ tên. Để trống để hệ thống tự tạo.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-categories".
 */
export interface SolutionCategory {
  id: number;
  name: string;
  /**
   * Tự sinh từ tên. Để trống để hệ thống tự tạo.
   */
  slug?: string | null;
  type: 'use_case' | 'industry' | 'compliance' | 'general';
  description?: string | null;
  /**
   * Số nhỏ hiển thị trước.
   */
  sortOrder?: number | null;
  status: 'draft' | 'published';
  catalogManaged?: boolean | null;
  catalogSource?: string | null;
  catalogSourcePath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Tự sinh từ tên. Để trống để hệ thống tự tạo.
   */
  slug?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  category?: (number | null) | Category;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Tối ưu hiển thị trên công cụ tìm kiếm và mạng xã hội.
   */
  seo?: {
    /**
     * Tiêu đề hiển thị trên Google (≈ 60 ký tự).
     */
    metaTitle?: string | null;
    /**
     * Mô tả ngắn hiển thị trên Google (≈ 160 ký tự).
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Để trống để dùng URL mặc định của trang.
     */
    canonical?: string | null;
  };
  publishedAt?: string | null;
  /**
   * Tự sinh từ tên. Để trống để hệ thống tự tạo.
   */
  slug?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  clientName: string;
  industry?: string | null;
  summary?: string | null;
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  results?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  testimonial?: {
    quote?: string | null;
    author?: string | null;
    role?: string | null;
  };
  relatedProducts?: (number | Product)[] | null;
  /**
   * Tối ưu hiển thị trên công cụ tìm kiếm và mạng xã hội.
   */
  seo?: {
    /**
     * Tiêu đề hiển thị trên Google (≈ 60 ký tự).
     */
    metaTitle?: string | null;
    /**
     * Mô tả ngắn hiển thị trên Google (≈ 160 ký tự).
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Để trống để dùng URL mặc định của trang.
     */
    canonical?: string | null;
  };
  logo?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  /**
   * Tự sinh từ tên. Để trống để hệ thống tự tạo.
   */
  slug?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  department?: string | null;
  location?: string | null;
  workType?: ('full-time' | 'part-time' | 'contract' | 'remote' | 'hybrid') | null;
  experienceLevel?: string | null;
  salaryRange?: string | null;
  summary?: string | null;
  responsibilities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  applicationEmail?: string | null;
  /**
   * Tối ưu hiển thị trên công cụ tìm kiếm và mạng xã hội.
   */
  seo?: {
    /**
     * Tiêu đề hiển thị trên Google (≈ 60 ký tự).
     */
    metaTitle?: string | null;
    /**
     * Mô tả ngắn hiển thị trên Google (≈ 160 ký tự).
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Để trống để dùng URL mặc định của trang.
     */
    canonical?: string | null;
  };
  publishedAt?: string | null;
  /**
   * Tự sinh từ tên. Để trống để hệ thống tự tạo.
   */
  slug?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  fullName: string;
  company?: string | null;
  email?: string | null;
  phone?: string | null;
  needType?: ('product' | 'solution' | 'consulting' | 'other') | null;
  companySize?: ('1-50' | '51-200' | '201-1000' | '1000+') | null;
  message?: string | null;
  sourcePage?: string | null;
  status?: ('new' | 'contacted' | 'in_progress' | 'closed') | null;
  internalNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: number;
  job?: (number | null) | Job;
  fullName: string;
  email?: string | null;
  phone?: string | null;
  portfolioUrl?: string | null;
  cvFile?: (number | null) | Media;
  coverMessage?: string | null;
  status?: ('new' | 'reviewing' | 'interview' | 'rejected' | 'hired') | null;
  internalNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'solution-categories';
        value: number | SolutionCategory;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: number | JobApplication;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  status?: T;
  catalogManaged?: T;
  catalogSource?: T;
  catalogSourcePath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  shortDescription?: T;
  overview?: T;
  keyPoints?:
    | T
    | {
        item?: T;
        id?: T;
      };
  features?:
    | T
    | {
        item?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        item?: T;
        id?: T;
      };
  detailSections?:
    | T
    | {
        heading?: T;
        body?: T;
        bullets?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  ctas?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  relatedProducts?: T;
  relatedSolutions?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
      };
  image?: T;
  sortOrder?: T;
  status?: T;
  catalogManaged?: T;
  catalogSource?: T;
  catalogSourcePath?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-categories_select".
 */
export interface SolutionCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  sortOrder?: T;
  status?: T;
  catalogManaged?: T;
  catalogSource?: T;
  catalogSourcePath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  shortDescription?: T;
  overview?: T;
  painPoints?:
    | T
    | {
        item?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        item?: T;
        id?: T;
      };
  detailSections?:
    | T
    | {
        heading?: T;
        body?: T;
        bullets?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  ctas?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  recommendedProducts?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
      };
  image?: T;
  sortOrder?: T;
  status?: T;
  catalogManaged?: T;
  catalogSource?: T;
  catalogSourcePath?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  category?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
      };
  publishedAt?: T;
  slug?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  clientName?: T;
  industry?: T;
  summary?: T;
  challenge?: T;
  solution?: T;
  results?:
    | T
    | {
        item?: T;
        id?: T;
      };
  testimonial?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
      };
  relatedProducts?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
      };
  logo?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  publishedAt?: T;
  slug?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  department?: T;
  location?: T;
  workType?: T;
  experienceLevel?: T;
  salaryRange?: T;
  summary?: T;
  responsibilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        item?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        item?: T;
        id?: T;
      };
  applicationEmail?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
      };
  publishedAt?: T;
  slug?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  fullName?: T;
  company?: T;
  email?: T;
  phone?: T;
  needType?: T;
  companySize?: T;
  message?: T;
  sourcePage?: T;
  status?: T;
  internalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  job?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  portfolioUrl?: T;
  cvFile?: T;
  coverMessage?: T;
  status?: T;
  internalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName?: string | null;
  tagline?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  linkedin?: string | null;
  facebook?: string | null;
  youtube?: string | null;
  ctaPrimary?: string | null;
  ctaSecondary?: string | null;
  defaultSeo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  tagline?: T;
  phone?: T;
  email?: T;
  address?: T;
  linkedin?: T;
  facebook?: T;
  youtube?: T;
  ctaPrimary?: T;
  ctaSecondary?: T;
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}